/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_12 (
    input [7:0] a,
    input [7:0] b,
    input [5:0] alufn,
    output reg [7:0] out
  );
  
  
  
  always @* begin
    out = 1'h0;
    
    case (alufn)
      6'h20: begin
        out = a << b[0+2-:3];
      end
      6'h21: begin
        out = a >> b[0+2-:3];
      end
      6'h23: begin
        out = a >> b[0+2-:3];
        out[7+0-:1] = a[7+0-:1];
      end
    endcase
  end
endmodule
